name: froot_app
description: froot account book application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.1.7 #onBoardingScreen
  table_calendar: ^3.0.9
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  percent_indicator: ^4.0.1


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - image/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
